[package]
name = "chess-sanity-check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
pest = "2.7.7"
pest_derive = "2.7.7"
