game = { "position"? ~ "fen" ~ fen ~ ("moves" ~ moves)? ~ ("verifymove" ~ verifymove)? ~ movestofen }
fen = { (!("moves" | "verifymove" | "movestofen") ~ ASCII)+ }

moves = { (!"moves" ~ move_part)+ }
verifymove = { !"verifymove" ~ move_part }
movestofen = { "movestofen" }

move_part = @{ (('a'..'h') ~ ('1'..'8')){2} ~ ("p" | "P" | "n" | "N" | "b" | "B" | "r" | "R" | "q" | "Q" | "k" | "K")? }
WHITESPACE = _{" "}
